import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="bg-white border border-gray-200 dark:bg-gray-800 dark:border-gray-700">
                <NextTopLoader color="#000" />
                <main className="container mx-auto max-w-3xl">{children}</main>
            </body>
        </html>
    );
}
